# syntax=docker/dockerfile:1.7
FROM node:20-alpine

WORKDIR /app
COPY package*.json ./

RUN --mount=type=secret,id=github_packages_token \
    TOKEN="$(cat /run/secrets/github_packages_token)" && \
    printf "@staark-inc:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=%s\n" "$TOKEN" > /root/.npmrc && \
    npm install --omit=dev && \
    rm -f /root/.npmrc

COPY . .

EXPOSE 3005
CMD ["npm", "run", "start"]